### PR TITLE
googleSynthesis with external audio stream

### PR DESCRIPTION
**Pull request by randaz81**
* googleSynthesis can now stream audio to an external player.

* added the parameter `--playbackmode`  which can assume the values `playFromDisk` (default), `sendToPort_compressed`, `sendToPort_uncompressed`

### CODE REVIEW

**Comment by randaz81** [comment]
@vtikha **The module compiles only with yarp master branch (future yarp 3.5).** 

So better not to merge this PR into master, if your master branch is supposed to work with yarp 3.4. 
Maybe a **devel** branch is more appropriate?

**Comment by pattacini** [comment]
We can merge it anyway and rely on the releases to get more stable versions of the code.

**Comment by pattacini** [comment]
Well, with a second thought this might cause problems @randaz81.
Even forging `devel` won't work as new devs we're doing will land there and should be working w/ yarp < 3.5.

**Comment by randaz81** [comment]
PR rebased onto master

**Comment by randaz81** [comment]
PR rebased onto master

**Comment by pattacini** [comment]
Our latest distro relies on YARP-3.6.0, thus it should be fine now to proceed with the review @vtikha.

**Comment by randaz81** [comment]
@pattacini @vtikha we are using yarp> 3.5 so I think that there are no more issues, can we merge this?

**Review by vtikha — APPROVED** [review]
LGTM

**Pull request merged**
