### PR TITLE
Svox speech

### PR DESCRIPTION
**Pull request by pattacini**
Thanks to @apaikan we have now a very light package in Linux for **speech synthesis** that can be run as a **yarp plugin** and exposes some nice features, among which I like to point out the **multi languages support** and the possibility to tune the **voice pitch and speed**.

##### Build
- Go in `svox-speech` directory and build according to the instructions you'll find therein.

##### Test
- See whether everything is correctly in place:
    - `yarp plugin --list` and `yarpdev --list` should list down `speech` as a plugin and/or device.
- Run: `yarpdev --device speech`
- Run: `iSpeak --package speech-dev`
- Run: `yarp connect /iSpeak/speech-dev/rpc /icub/speech:rpc`
- Test: `echo "this is a test" | yarp write ... /iSpeak`

cc @robotology/wysiwyd-developers @vtikha

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
Very cool. Thanks @apaikan!
@gregoire-pointeau: Can you please try whether this works nicely in Lyon? If it works, we should change the XML file of the year 2 demo accordingly.

**Comment by gregoire-pointeau** [comment]
I won't be at the lab today, but I'll do it tomorrow morning.

**Comment by gregoire-pointeau** [comment]
I confirm, it working fine.

**Comment by pattacini** [comment]
Great :tada: 
Thanks :exclamation:

**Comment by pattacini** [comment]
I've made an attempt to make it run also on windows systems but didn't test it yet.

**Comment by gsaponaro** [comment]
Cool! It's working here too.
Is it possible to add Portuguese to the list of supported languages?

**Comment by pattacini** [comment]
we can ask @apaikan whether he can retrieve Portuguese archives as well.

**Comment by gregoire-pointeau** [comment]
I come back on what I said.
The tests in the README is doing fine. I can tune the voice and speak normally through `/icub/speech:rpc`.
But when I launch: `echo "this is a test" | yarp write ... /iSpeak`, the robot only says: "this".

**Comment by pattacini** [comment]
Try not to do that using `echo` but directly sending the sentence to `/iSpeak`.
It was working here (didn't test with `echo` though)

**Comment by Tobias-Fischer** [comment]
Try `echo "\"this is a test\"" | yarp write ... /iSpeak` and it should say "this is a test" rather than just "this".

**Comment by gregoire-pointeau** [comment]
Ok indeed it was a problem coming from `\"`.

**Comment by pattacini** [comment]
Great then!
I've updated the instructions above.

**Pull request merged**
